# Generated by Django 3.2.9 on 2022-02-08 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='token',
            new_name='qr_token',
        ),
    ]
