# Generated by Django 3.2.9 on 2022-02-08 02:36

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_token_profile_qr_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='qr',
            field=models.ImageField(blank=True, upload_to=users.models.user_directory_path),
        ),
    ]
